source $HOME/.vim/config/mappings.vim
source $HOME/.vim/plugins.vim
source $HOME/.vim/config/plugins.vim
source $HOME/.vim/config/display.vim

" change swap file location
set directory=$HOME/.vim/.swapfiles//
 " change backup file location
set backupdir=$HOME/.vim/.backups//
