source $HOME/.vim/plugins.vim
source $HOME/.vim/config/plugins.vim
source $HOME/.vim/config/display.vim

" change swap file location
set directory=./.swapfiles//
 " change backup file location
set backupdir=./.backups//
