source $HOME/.vim/plugins.vim
source $HOME/.vim/config/plugins.vim
source $HOME/.vim/config/display.vim

" change swap file location
set directory=$PWD/.swapfiles//
 " change backup file location
set backupdir=$PWD/.backups//
