export PATH=/usr/local/bin:$HOME/bin:$PATH

# Path to oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
# custom theme
ZSH_THEME="zeb2"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  nvm
  git
)

source $ZSH/oh-my-zsh.sh

# aliases
# git 
alias status="git status"
alias add="git add"
alias commit="git commit"
alias pull="git pull"
alias push="git push"
alias diff="git diff --"
alias switch="git switch"
alias stash="git stash"
alias pop="git stash pop"
alias rebase="git rebase"

# misc
alias weather="curl wttr.in"
alias restart="exec zsh"

# navigation
alias dotfiles="cd ~/dev/dotfiles"
alias under="cd ~/dev/underwriter"

# Launch VSC from iterm
function code {
    if [[ $# = 0 ]]
        then
             open -a "Visual Studio Code"
     else
        local argPath="$1"
        [[ $1 = /* ]] && argPath="$1" || argPath="$PWD/${1#./}"
        open -a "Visual Studio Code" "$argPath"
    fi
}

eval "$(direnv hook zsh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
