export PATH=$HOME/bin:/usr/local/bin:/usr/local/opt/python/libexec/bin:$PATH

# Path to oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# custom command prompt
ZSH_THEME="zeb2"

# Plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# aliases
# git 
alias status="git status"
alias add="git add"
alias commit="git commit"
alias pull="git pull"
alias push="git push"
alias diff="git diff --"
alias switch="git switch"
alias stash="git stash"
alias pop="git stash pop"
alias rebase="git rebase"
alias restore="git restore"

# misc
alias weather="curl wttr.in"
alias restart="exec zsh"

# navigation
alias dotfiles="cd ~/dev/dotfiles"

# Launch VSC from iterm
function code {
    if [[ $# = 0 ]]
        then
             open -a "Visual Studio Code"
     else
        local argPath="$1"
        [[ $1 = /* ]] && argPath="$1" || argPath="$PWD/${1#./}"
        open -a "Visual Studio Code" "$argPath"
    fi
}

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# ST specific
alias under="cd ~/dev/underwriter"
alias over="cd ~/dev/overwriter"
alias msp="mo script --project $@"
alias clear-dev-db="mo script --project athena_data clear-dev-db"
alias seed-dev-db="mo script --project athena_data seed-dev-db"
eval "$(direnv hook zsh)"

